feat:  downloading video collections
jingfelix/BiliFM pull request #15
Opened 2024-03-22 13:06 UTC by robo-dani

Add functionality for downloading video collections.

增加了下载视频合集的功能,  对应的命令是 season(因为b站的api是 season_archive...),  因为视频可能会很多, 所以会以合集名创建相应的文件夹保存.
同时支持 `-o $dir` 选择下载目录.

2024-03-22 13:08 UTC, robo-dani commented
b站 视频合集与列表居然是两个东西, 本身想把列表的也写了, 但是相应api给的是aid, 就摆了.

2024-03-23 07:06 UTC, jingfelix commented
我用 README 里的数据测试时报了这个错：
<img width="437" alt="image" src="https://github.com/jingfelix/BiliFM/assets/72600955/0992e4cb-9052-4b78-b98e-fe33e2b500fc">

2024-03-23 07:25 UTC, robo-dani commented
不太清楚 我在我的两个设备上都能通过, 你能在 season.py的37行加入  ` typer.echo(f"code: {res['code']}")` 吗, 我只打印了错误时的message
另外-352 我 在 api介绍里看到是请求被拦截了 https://github.com/SocialSisterYi/bilibili-API-collect/blob/26f4f65da4312cbeb149ece6b33c022330a8e7a2/docs/user/relation.md?plain=1#L229

2024-03-23 07:27 UTC, jingfelix requested changes

2024-03-23 07:31 UTC, jingfelix commented
> typer.echo(f"code: {res['code']}")

我又跑了下，这次又能下载了，可能是我被风控了……？

2024-03-23 07:33 UTC, robo-dani commented
笑死, 神奇的b站, 不过我完善以下错误信息吧

说起来我下载特别多的合集的时候也怕触发风控什么的,

2024-03-23 07:43 UTC, robo-dani commented
都改好了, 麻烦再检查一下吧

2024-03-23 07:51 UTC, jingfelix approved these changes

2024-03-23 07:52 UTC, merged